In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [26]:
df = pd.read_csv("C:/Users/LENOVO/Downloads/train.csv")

In [28]:
df["Title"] = df["Name"].str.extract(" ([A-Za-z]+)\.", expand=False)
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11036\1798611418.py:1: SyntaxWarning: invalid escape sequence '\.'
  df["Title"] = df["Name"].str.extract(" ([A-Za-z]+)\.", expand=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

In [31]:
df = df.drop(columns = ['Cabin', 'Name'])

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Title
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,S,Mr
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C,Mrs
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S,Miss
3,4,1,1,female,35.0,1,0,113803,53.1000,S,Mrs
4,5,0,3,male,35.0,0,0,373450,8.0500,S,Mr

In [33]:
df = df.drop(columns = ['Ticket'])

In [36]:
df['Age'] = df['Age'].fillna(
    df.groupby("Title")["Age"].transform("median")
)

df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df = df.drop(columns = ["PassengerId"])
df = pd.get_dummies(df, columns = ['Sex', 'Embarked', 'Title'], drop_first= True)
df = df.astype(int)
df['Fare'] = np.log1p(df['Fare'])

In [92]:
df.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S,Title_Col,...,Title_Major,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir
0,0,3,22,1,0,2.079442,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0
1,1,1,38,1,0,4.276666,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,1,3,26,0,0,2.079442,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
3,1,1,35,1,0,3.988984,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
4,0,3,35,0,0,2.197225,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0

In [54]:
X_train = df.drop(columns = 'Survived', axis = 1)
y_train = df['Survived']

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [52]:
pipe = Pipeline(steps = [
    ('classifier', LogisticRegression(solver = 'liblinear'))
])

In [55]:
pipe.fit(X_train, y-train)

Pipeline(steps=[('classifier', LogisticRegression(solver='liblinear'))])

#

# Test Data

In [85]:
test_df = pd.read_csv("C:/Users/LENOVO/Downloads/test.csv")

In [100]:
test = pd.read_csv("C:/Users/LENOVO/Downloads/test.csv")

In [86]:
test_df["Title"] = test_df["Name"].str.extract(" ([A-Za-z]+)\.", expand=False)

<>:1: SyntaxWarning: invalid escape sequence '\.'
<>:1: SyntaxWarning: invalid escape sequence '\.'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_11036\3300747330.py:1: SyntaxWarning: invalid escape sequence '\.'
  test_df["Title"] = test_df["Name"].str.extract(" ([A-Za-z]+)\.", expand=False)

In [87]:

test_df = test_df.drop(columns = ['Cabin', 'Name'])
test_df = test_df.drop(columns = ['Ticket'])
test_df["Age"] = test_df["Age"].fillna(df["Age"].median())


test_df["Fare"] = test_df["Fare"].fillna(df["Fare"].median())

test_df["Embarked"] = test_df["Embarked"].fillna(test_df["Embarked"].mode()[0])
test_df = test_df.drop(columns = ["PassengerId"])
test_df = pd.get_dummies(test_df, columns = ['Sex', 'Embarked', 'Title'], drop_first= True)

In [88]:
test_df.isna().sum()

Pclass          0
Age             0
SibSp           0
Parch           0
Fare            0
Sex_male        0
Embarked_Q      0
Embarked_S      0
Title_Dona      0
Title_Dr        0
Title_Master    0
Title_Miss      0
Title_Mr        0
Title_Mrs       0
Title_Ms        0
Title_Rev       0
dtype: int64

In [89]:
test_df = test_df.astype(int)
test_df['Fare'] = np.log1p(test_df['Fare'])

In [90]:
test_df

,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S,Title_Dona,Title_Dr,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Ms,Title_Rev
0,3,34,0,0,2.079442,1,1,0,0,0,0,0,1,0,0,0
1,3,47,1,0,2.079442,0,0,1,0,0,0,0,0,1,0,0
2,2,62,0,0,2.302585,1,1,0,0,0,0,0,1,0,0,0
3,3,27,0,0,2.197225,1,0,1,0,0,0,0,1,0,0,0
4,3,22,1,1,2.564949,0,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,3,30,0,0,2.197225,1,0,1,0,0,0,0,1,0,0,0
414,1,39,0,0,4.691348,0,0,0,1,0,0,0,0,0,0,0
415,3,38,0,0,2.079442,1,0,1,0,0,0,0,1,0,0,0
416,3,30,0,0,2.197225,1,0,1,0,0,0,0,1,0,0,0
417,3,30,1,1,3.135494,1,0,0,0,0,1,0,0,0,0,0

In [94]:
test_df = test_df.reindex(columns=X_train.columns, fill_value=0)

In [95]:
y_pred = pipe.predict(test_df)

In [96]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1])

In [98]:
np.unique(y_pred, return_counts = True)

(array([0, 1]), array([252, 166]))

In [102]:
submission = pd.DataFrame({
    "PassengerId": test["PassengerId"],
    "Survived": y_pred
})
print(submission)

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]

In [103]:
submission.to_csv(r"C:\Users\LENOVO\Downloads\submission.csv", index=False)